# Generated by Django 3.2.2 on 2022-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20211215_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department_name',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE')], default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type_data',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('HOD', 'HOD')], max_length=20),
        ),
    ]
