# Generated by Django 3.2.2 on 2022-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20220228_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=15)),
                ('candidate_type', models.CharField(max_length=15)),
                ('leave_reason', models.CharField(max_length=350)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_id']},
        ),
    ]
