# Generated by Django 4.0.3 on 2022-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_leaves_status_alter_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('ASSISTANT PROFESSOR', 'Ass Prof'), ('PROFESSOR', 'Prof'), ('Doctarate', 'Dr')], default="'Ass Prof'", max_length=50),
        ),
    ]
